stages:
  - build

build_job:
  stage: build
  only:
    - master
  script:
    - DEV_HOME="/var/www/app.crazypush.com";
    - if [ ! -d $DEV_HOME ]; then exit 1; fi
    - PATH=${PATH}:/usr/local/bin
    - npm install
    - npm run build:ssr
    - whoami
    - ls dist/*
    - pwd
    - rsync -arp  --exclude-from='.rsync_excludes' . ${DEV_HOME}
    - pm2 restart web
